services:
  core.breadcrumb:
    class: ACP3\Core\Breadcrumb\Steps
    arguments:
      - '@service_container'
      - '@core.lang'
      - '@core.http.request'
      - '@core.router'
      - '@core.event_dispatcher'

  core.breadcrumb.title:
    class: ACP3\Core\Breadcrumb\Title
    arguments:
      - '@core.event_dispatcher'
      - '@core.breadcrumb'
