services:
  core.helpers.view.checkAccess:
    class: ACP3\Core\Helpers\View\CheckAccess
    arguments:
      - '@core.acl'
      - '@core.lang'
      - '@core.router'

  core.helpers.alerts:
    class: ACP3\Core\Helpers\Alerts
    arguments:
      - '@core.request'
      - '@core.view'

  core.helpers.date:
    class: ACP3\Core\Helpers\Date
    arguments:
      - '@core.date'
      - '@core.lang'
      - '@core.request'
      - '@core.helpers.forms'
      - '@core.validation.validation_rules.date_validation_rule'

  core.helpers.forms:
    class: ACP3\Core\Helpers\Forms
    arguments:
      - '@core.lang'
      - '@core.request'

  core.helpers.sendEmail:
    class: ACP3\Core\Helpers\SendEmail
    arguments:
      - '@core.mailer'

  core.helpers.redirect:
    class: ACP3\Core\Helpers\RedirectMessages
    arguments:
      - '@core.http.redirect_response'
      - '@core.request'
      - '@core.session'

  core.helpers.secure:
    class: ACP3\Core\Helpers\Secure

  core.helpers.formToken:
    class: ACP3\Core\Helpers\FormToken
    arguments:
      - '@core.request'
      - '@core.session'

  core.helpers.pageBreaks:
    class: ACP3\Core\Helpers\PageBreaks
    arguments:
      - '@core.request'
      - '@core.router'
      - '@core.helpers.toc'

  core.helpers.sort:
    class: ACP3\Core\Helpers\Sort
    arguments:
      - '@core.db'

  core.helpers.toc:
    class: ACP3\Core\Helpers\TableOfContents
    arguments:
      - '@core.breadcrumb.title'
      - '@core.lang'
      - '@core.request'
      - '@core.router'
      - '@core.validation.validation_rules.integer_validation_rule'
      - '@core.view'

  core.helpers.stringFormatter:
    class: ACP3\Core\Helpers\StringFormatter

  core.helpers.formatter.dateRange:
    class: ACP3\Core\Helpers\Formatter\DateRange
    arguments:
      - '@core.date'
      - '@core.lang'

  core.helpers.formatter.mark_entries:
    class: ACP3\Core\Helpers\Formatter\MarkEntries
    arguments:
      - '@core.lang'

  core.helpers.formatter.rewriteInternalUri:
    class: ACP3\Core\Helpers\Formatter\RewriteInternalUri
    arguments:
      - '@core.environment.application_path'
      - '@core.modules.helper.controllerActionExists'
      - '@core.request'
      - '@core.router'
      - '@seo.validation.validation_rules.uri_alias_validation_rule'
