services:
  emoticons.event.on_emoticons_model_after_delete_listener:
    class: ACP3\Modules\ACP3\Emoticons\Event\Listener\OnEmoticonsModelAfterDeleteListener
    arguments:
      - '@emoticons.cache'
    tags:
      - { name: core.eventListener, event: emoticons.model.emoticons.after_delete, method: execute }

  emoticons.event.on_emoticons_model_before_delete_listener:
    class: ACP3\Modules\ACP3\Emoticons\Event\Listener\OnEmoticonsModelBeforeDeleteListener
    arguments:
      - '@core.environment.application_path'
      - '@emoticons.model.emoticonrepository'
    tags:
      - { name: core.eventListener, event: emoticons.model.emoticons.before_delete, method: execute }

  emoticons.event.on_wysiwyg_textarea_before_listener:
    class: ACP3\Modules\ACP3\Emoticons\Event\Listener\OnWysiwygTextareaBeforeListener
    arguments:
      - '@core.modules'
      - '@emoticons.helpers'
    tags:
      - { name: core.eventListener, event: core.wysiwyg.textarea.before, method: onWysiwygTextareaBefore }

  emoticons.event.on_render_emoticons_list_listener:
    class: ACP3\Modules\ACP3\Emoticons\Event\Listener\RenderEmoticonsListListener
    arguments:
      - '@emoticons.helpers'
    tags:
      - { name: core.eventListener, event: emoticons.render_emoticons_list, method: renderEmoticonsList }

  emoticons.event.update_emoticons_cache_on_model_after_save_listener:
    class: ACP3\Modules\ACP3\Emoticons\Event\Listener\UpdateEmoticonsCacheOnModelAfterSaveListener
    arguments:
      - '@emoticons.cache'
    tags:
      - { name: core.eventListener, event: emoticons.model.emoticons.after_save, method: execute }
