services:
  emoticons.model.data_grid_repository:
    class: ACP3\Modules\ACP3\Emoticons\Model\Repository\DataGridRepository
    arguments:
      - '@core.db'

  emoticons.model.emoticonrepository:
    class: ACP3\Modules\ACP3\Emoticons\Model\Repository\EmoticonRepository
    arguments:
      - '@core.db'

  emoticons.model:
    class: ACP3\Modules\ACP3\Emoticons\Model\EmoticonsModel
    arguments:
      - '@core.event_dispatcher'
      - '@core.helpers.secure'
      - '@emoticons.model.emoticonrepository'
