services:
  articles.controller.admin.index.create:
    class: ACP3\Modules\ACP3\Articles\Controller\Admin\Index\Create
    arguments:
      - '@core.context.admin'
      - '@core.helpers.forms'
      - '@articles.model'
      - '@articles.validator'
      - '@core.helpers.formToken'
    calls:
      - ['setManageMenuItemHelper', ['@?menus.helpers.managemenuitem']]
      - ['setMenusCache', ['@?menus.cache']]
      - ['setMenuItemFormFieldsHelper', ['@?menus.helpers.menuitemformfields']]
      - ['setMetaFormFieldsHelper', ['@?seo.helper.meta_form_fields']]
      - ['setUriAliasManager', ['@?seo.helper.uri_alias_manager']]

  articles.controller.admin.index.delete:
    class: ACP3\Modules\ACP3\Articles\Controller\Admin\Index\Delete
    arguments:
      - '@core.context.admin'
      - '@articles.model'

  articles.controller.admin.index.edit:
    class: ACP3\Modules\ACP3\Articles\Controller\Admin\Index\Edit
    arguments:
      - '@core.context.admin'
      - '@core.helpers.forms'
      - '@articles.model'
      - '@articles.validator'
      - '@core.helpers.formToken'
    calls:
      - ['setManageMenuItemHelper', ['@?menus.helpers.managemenuitem']]
      - ['setMenusCache', ['@?menus.cache']]
      - ['setMenuItemFormFieldsHelper', ['@?menus.helpers.menuitemformfields']]
      - ['setMenuItemRepository', ['@?menus.model.menuitemrepository']]
      - ['setMetaFormFieldsHelper', ['@?seo.helper.meta_form_fields']]
      - ['setUriAliasManager', ['@?seo.helper.uri_alias_manager']]

  articles.controller.admin.index.index:
    class: ACP3\Modules\ACP3\Articles\Controller\Admin\Index\Index
    arguments:
      - '@core.context.admin'
      - '@articles.model.data_grid_repository'

  articles.controller.frontend.index.details:
    class: ACP3\Modules\ACP3\Articles\Controller\Frontend\Index\Details
    arguments:
      - '@core.context.frontend'
      - '@core.date'
      - '@core.helpers.pageBreaks'
      - '@articles.model.articlerepository'
      - '@articles.cache'

  articles.controller.frontend.index.index:
    class: ACP3\Modules\ACP3\Articles\Controller\Frontend\Index\Index
    arguments:
      - '@core.context.frontend'
      - '@core.date'
      - '@core.pagination'
      - '@articles.model.articlerepository'

  articles.controller.widget.index.index:
    class: ACP3\Modules\ACP3\Articles\Controller\Widget\Index\Index
    arguments:
      - '@core.context.widget'
      - '@core.date'
      - '@articles.model.articlerepository'
      - '@articles.cache'

  articles.controller.widget.index.single:
    class: ACP3\Modules\ACP3\Articles\Controller\Widget\Index\Single
    arguments:
      - '@core.context.widget'
      - '@core.date'
      - '@articles.model.articlerepository'
      - '@articles.cache'
