services:
  update.model.schema_update_model:
    class: ACP3\Installer\Modules\Update\Model\SchemaUpdateModel
    arguments:
      - '@core.environment.application_path'
      - '@core.xml'
      - '@core.modules.vendors'
      - '@core.modules'
      - '@core.modules.schemaUpdater'
