services:
  smarty.plugin.add_protocol:
    class: ACP3\Core\View\Renderer\Smarty\Modifiers\PrefixUri
    tags:
      - { name: core.view.extension }

  smarty.plugin.nl2p:
    class: ACP3\Core\View\Renderer\Smarty\Modifiers\Nl2p
    arguments: ['@core.helpers.string_formatter']
    tags:
      - { name: core.view.extension }

  smarty.plugin.rewrite_uri:
    class: ACP3\Core\View\Renderer\Smarty\Modifiers\RewriteUri
    arguments: ['@core.helpers.formatter.rewrite_internal_uri']
    tags:
      - { name: core.view.extension }
