services:
  polls.controller.admin.index.create:
    class: ACP3\Modules\ACP3\Polls\Controller\Admin\Index\Create
    arguments:
      - '@core.context.admin'
      - '@core.date'
      - '@core.helpers.forms'
      - '@core.helpers.formToken'
      - '@polls.model.pollrepository'
      - '@polls.model.answerrepository'
      - '@polls.model.voterepository'
      - '@polls.validator'

  polls.controller.admin.index.delete:
    class: ACP3\Modules\ACP3\Polls\Controller\Admin\Index\Delete
    arguments:
      - '@core.context.admin'
      - '@polls.model.pollrepository'

  polls.controller.admin.index.edit:
    class: ACP3\Modules\ACP3\Polls\Controller\Admin\Index\Edit
    arguments:
      - '@core.context.admin'
      - '@core.date'
      - '@core.helpers.forms'
      - '@core.helpers.formToken'
      - '@polls.model.pollrepository'
      - '@polls.model.answerrepository'
      - '@polls.model.voterepository'
      - '@polls.validator'

  polls.controller.admin.index.index:
    class: ACP3\Modules\ACP3\Polls\Controller\Admin\Index\Index
    arguments:
      - '@core.context.admin'
      - '@polls.model.data_grid_repository'

  polls.controller.frontend.index.index:
    class: ACP3\Modules\ACP3\Polls\Controller\Frontend\Index\Index
    arguments:
      - '@core.context.frontend'
      - '@core.date'
      - '@polls.model.pollrepository'
      - '@polls.model.voterepository'

  polls.controller.frontend.index.result:
    class: ACP3\Modules\ACP3\Polls\Controller\Frontend\Index\Result
    arguments:
      - '@core.context.frontend'
      - '@core.date'
      - '@polls.model.pollrepository'
      - '@polls.model.answerrepository'

  polls.controller.frontend.index.vote:
    class: ACP3\Modules\ACP3\Polls\Controller\Frontend\Index\Vote
    arguments:
      - '@core.context.frontend'
      - '@core.date'
      - '@polls.model.pollrepository'
      - '@polls.model.answerrepository'
      - '@polls.model.voterepository'

  polls.controller.widget.index.index:
    class: ACP3\Modules\ACP3\Polls\Controller\Widget\Index\Index
    arguments:
      - '@core.context.widget'
      - '@core.date'
      - '@polls.model.pollrepository'
      - '@polls.model.answerrepository'
      - '@polls.model.voterepository'

